/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.navegador.Pagina;

/**
 *
 * @author User
 */
public class VPagina extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VPagina.class.getName());
        private ControladorPagina controladorPagina;
    /**
     * Creates new form Vista_Pagina
     */
    public VPagina() {
        initComponents();
         Pagina modelo = new Pagina("Inicio");
        controladorPagina = new ControladorPagina(this, modelo);
    }
 public void setControlador(ControladorPagina controladorPagina) {
        this.controladorPagina = controladorPagina;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anteriorbtn = new javax.swing.JButton();
        agregarbtn = new javax.swing.JButton();
        paginalbl = new javax.swing.JLabel();
        paginatxt = new javax.swing.JTextField();
        Pagina_actual = new javax.swing.JTextField();
        cerrarbtn = new javax.swing.JButton();
        siguientebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        anteriorbtn.setText("Anterior");
        anteriorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorbtnActionPerformed(evt);
            }
        });

        agregarbtn.setText("Agregar");
        agregarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarbtnActionPerformed(evt);
            }
        });

        paginalbl.setText("Pagina actual");

        Pagina_actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pagina_actualActionPerformed(evt);
            }
        });

        cerrarbtn.setText("Cerrar");
        cerrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarbtnActionPerformed(evt);
            }
        });

        siguientebtn.setText("Siguiente");
        siguientebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(anteriorbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguientebtn)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(paginatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(agregarbtn)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrarbtn)
                    .addComponent(Pagina_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paginalbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarbtn)
                    .addComponent(paginatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(paginalbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Pagina_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorbtn)
                    .addComponent(siguientebtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cerrarbtn)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pagina_actualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pagina_actualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pagina_actualActionPerformed

    private void cerrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarbtnActionPerformed
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_cerrarbtnActionPerformed

    private void agregarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarbtnActionPerformed
     if (controladorPagina != null) {
            controladorPagina.procesoControladorPagina();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_agregarbtnActionPerformed

    private void anteriorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorbtnActionPerformed
     if(controladorPagina != null){
         controladorPagina.navegarAtras();}
// TODO add your handling code here:
    }//GEN-LAST:event_anteriorbtnActionPerformed

    private void siguientebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientebtnActionPerformed
         if (controladorPagina != null) {
        controladorPagina.navegarAdelante();
    }// TODO add your handling code here:
    }//GEN-LAST:event_siguientebtnActionPerformed
    public String getpaginatxt() {
        return paginatxt.getText();
    }

    public void setPaginaActual(String texto) {
        Pagina_actual.setText(texto);
    }

    public void limpiarCampoTexto() {
        paginatxt.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pagina_actual;
    private javax.swing.JButton agregarbtn;
    private javax.swing.JButton anteriorbtn;
    private javax.swing.JButton cerrarbtn;
    private javax.swing.JLabel paginalbl;
    private javax.swing.JTextField paginatxt;
    private javax.swing.JButton siguientebtn;
    // End of variables declaration//GEN-END:variables
}
